### ISSUE TITLE
Implémenter la ressource modifier une affaire

### ISSUE THREAD

**Issue by emchateau** [publicarchi/cbc-webapp#4]
- Titre
- Type administratif
- Localisation 
  - Département
  - Ville
- Typologie
- Dates
- Note
- Biblio

**Comment by WilliamDiakite** [comment]
Une ressource permet de créer une affaire.
> commit 6d881d54e8430ecbed47006d8a3db6a23827bff1
Author: emchateau
Date:   Mon Mar 14 08:42:49 2022 -0400

Il faut cependant l'améliorer pour permettre les mises à jour d'une affaire

**Comment by WilliamDiakite** [comment]
La resource de mise à jour d'une affaire a été implémentée. Elle comporte néamoins un bug mineur : l'id de l'affaire est présent à deux endroits après la mise à jour de l'affaire : 1. en tant que xml:id d'une affaire et 2. en tant qu'objet à l'intérieur de l'affaire.



La ligne ci-dessous semble être en cause :
```xquery
<affair xml:id="{$id}">
      {json:parse($content, map{ 'merge': fn:true() })/*[fn:not(self::id)]/node()}
</affair>
```

qui produit cet exemple de résultat : 
```xml
<affair xmlns="http://conbavil.fr/namespace" xmlns:fonc="http://conbavil.fr/fn" xml:id="id9d3210771">
  <head>Super affaire</head>
  <id>id9d3210771</id> // cette ligne ne devrait pas être présente
  <localisation>
    <commune>Mijouxfsdfsdfsdfsdf</commune>
    <departementDecimal/>
    <departementAncien/>
    <departement>45</departement>
    <region/>
  </localisation>
  <deliberations>
    <_>conbavil00104</_>
    <_>conbavil00101</_>
    <_>conbavil00102</_>
  </deliberations>
  <types/>
  <meta>
    <user>
      <id>1</id>
      <name>William</name>
      <email>will@gmail.com</email>
    </user>
    <action>modification</action>
    <date>1994-11-05T13:15:30Z</date>
  </meta>
</affair>
```
`[fn:not(self::id)]` n'est pas pris en compte. @emchateau, as-tu une idée de comment régler ça ?

**Comment by WilliamDiakite** [comment]
Réglé avec le commit e132ae1b5827c4fe0e96e064a5941690f0b50fc2
