### ISSUE TITLE
Implémenter une ressource de recommandation pour les affaires

### ISSUE THREAD

**Issue by emchateau** [publicarchi/cbc-webapp#7]
Recommander des regroupements d’affaires à partir des ids

**Comment by WilliamDiakite** [comment]
La ressource (post) `/cbc/affaires/fromDeliberations` permet de retrouver les affaires attachées à des délibérations passées dans le corps de la requête post.

 > commit 233ddb7558447f41700d75fe624cd2cd38845980 - adds ressource /cbc/affaires/fromDeliberations
Author: William Diakité 
Date:   Thu Mar 31 13:29:12 2022 -0400

Je ferme l'issue pour le moment, elle pourra être réouverte si la ressource citée plus haut ne résout pas la question des suggestions d'affaires.
